# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'employee-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for employee-app

  target 'employee-appTests' do
    inherit! :search_paths
    # Pods for testing
  
    
    
    # pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  end

end
