name: Codepush-TEST

on:
 workflow_dispatch:
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_DEV }}
  APP_NAME: ${{ 'Unipe/EmployeeApp' }}

jobs:
  getversion:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      target_version: ${{ steps.setoutput.outputs.target_version }}

  update-android:
    name: Update Android
    needs: getversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Codepush Update
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a ${{ env.APP_NAME}} -d Dev  
        env:
          APPCENTER_ACCESS_TOKEN: ${{ env.APP_CENTER_TOKEN }}
  
